name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: pw-tests:1
        
    - name: Run tests
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        HTTP_USER_NAME: ${{ secrets.HTTP_USER_NAME }}
        HTTP_PASSWORD: ${{ secrets.HTTP_PASSWORD }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: |
        docker run -e BASE_URL="${BASE_URL}" -e HTTP_USER_NAME="${HTTP_USER_NAME}" -e HTTP_PASSWORD="${HTTP_PASSWORD}" -e USER_EMAIL="${USER_EMAIL}" -e USER_PASSWORD="${USER_PASSWORD}" pw-tests:1
      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30