name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: pw-tests:1
        
    - name: Run tests
      run: |
        docker run pw-tests:1
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        HTTP_USER_NAME: ${{ secrets.HTTP_USER_NAME }}
        HTTP_PASSWORD: ${{ secrets.HTTP_PASSWORD }}
